"""Add timestamp ID column to run

Revision ID: 19e1c3bf902e
Revises: c55d1e6736c9
Create Date: 2023-02-17 06:57:05.568695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19e1c3bf902e'
down_revision = 'c55d1e6736c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('timestamp_id', sa.String(), nullable=False))
    op.alter_column('run', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('run', 'timestamp_id')
    # ### end Alembic commands ###
