"""Add name column to check table

Revision ID: 2ac625753917
Revises: 9b503b1cec1a
Create Date: 2023-02-05 08:26:49.404840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac625753917'
down_revision = '9b503b1cec1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'name')
    # ### end Alembic commands ###
