"""Add enable column to task

Revision ID: 3ae8d25812d5
Revises: d0da37953fd4
Create Date: 2023-02-24 06:20:51.403615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae8d25812d5'
down_revision = 'd0da37953fd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'enabled')
    # ### end Alembic commands ###
