"""Add check table

Revision ID: 9b503b1cec1a
Revises: 
Create Date: 2023-02-04 11:39:02.888429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b503b1cec1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check')
    # ### end Alembic commands ###
