"""Add client column to check table

Revision ID: 9d0524f5b53c
Revises: 19e1c3bf902e
Create Date: 2023-02-19 07:30:57.941537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9d0524f5b53c'
down_revision = '19e1c3bf902e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    clienttype_enum = postgresql.ENUM('BROWSER_FIREFOX', 'REQUESTS', name='clienttype', create_type=False)
    clienttype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('check', sa.Column('client', sa.Enum('BROWSER_FIREFOX', 'REQUESTS', name='clienttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'client')
    # ### end Alembic commands ###
