"""Add database table for run.

Revision ID: c55d1e6736c9
Revises: fff378220a8b
Create Date: 2023-02-16 06:52:40.345648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55d1e6736c9'
down_revision = 'fff378220a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['check.id'], name='fk_run_check_id_check_id'),
    sa.PrimaryKeyConstraint('check_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run')
    # ### end Alembic commands ###
