"""Add interval field to check table

Revision ID: fff378220a8b
Revises: 3bc55597348d
Create Date: 2023-02-15 17:20:33.370100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff378220a8b'
down_revision = '3bc55597348d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'interval')
    # ### end Alembic commands ###
